# path of raw data which will be used for training model
data:
  raw_data_path: 'data/raw/Salary_Data.csv'
  processed_data_path: 'data/processed/salary_data.csv'
  train_data_path: 'data/processed/train.csv'
  test_data_path: 'data/processed/test.csv'

# model training parameters
model:
  model_dir: 'models/'
  model_name: 'salary_predictor'
  test_size: 0.2
  random_state: 42

# mlflow parameters
mlflow:
  tracking_uri: 'http://localhost:8000'
  experiment_name: 'salary_prediction'
  registry_uri: 'mlflow_model_registry'

# model testing api parameters
api:
  host: '0.0.0.0'
  port: 8000
  reload: true

# monitoring parameters
monitoring:
  drift_threshold: 0.1
  metrics_interval: 24
